In [9]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

df = pd.read_csv("Datos/pokemon2.csv", nrows = 100000)
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [19]:
# 2Da opcion:
types1 = pd.get_dummies(df["Type 1"])
types2 = pd.get_dummies(df["Type 2"])
pd.set_option('max_rows', None)
pd.reset_option('max_rows')
types = types1 | types2


df_clean = pd.merge(df, types, left_index=True, right_index=True)

df_clean.dropna(thresh=28,inplace=True)
df_clean.drop(["Type 1", "Type 2"], axis = 1,inplace= True)
df_clean

,#,Name,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,...,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
0,1,Bulbasaur,45,49,49,65,65,45,1,False,...,0,1,0,0,0,1,0,0,0,0
1,2,Ivysaur,60,62,63,80,80,60,1,False,...,0,1,0,0,0,1,0,0,0,0
2,3,Venusaur,80,82,83,100,100,80,1,False,...,0,1,0,0,0,1,0,0,0,0
3,4,Mega Venusaur,80,100,123,122,120,80,1,False,...,0,1,0,0,0,1,0,0,0,0
4,5,Charmander,39,52,43,60,50,65,1,False,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,50,100,150,100,150,50,6,True,...,0,0,0,0,0,0,0,1,0,0
796,797,Mega Diancie,50,160,110,160,110,110,6,True,...,0,0,0,0,0,0,0,1,0,0
797,798,Hoopa Confined,80,110,60,150,130,70,6,True,...,1,0,0,0,0,0,1,0,0,0
798,799,Hoopa Unbound,80,160,60,170,130,80,6,True,...,0,0,0,0,0,0,1,0,0,0
799,800,Volcanion,80,110,120,130,90,70,6,True,...,0,0,0,0,0,0,0,0,0,1

In [25]:
df_fights = pd.read_csv("Datos/combats.csv", nrows = 100000)
df_fights

       First_pokemon  Second_pokemon  Winner
0                266             298     298
1                702             701     701
2                191             668     668
3                237             683     683
4                151             231     151
...              ...             ...     ...
49995            707             126     707
49996            589             664     589
49997            303             368     368
49998            109              89     109
49999              9              73       9

[50000 rows x 3 columns]

In [ ]:
clf = tree.DecisionTreeClassifier()

# Entrenaremos el objeto clf utilizando el mÃ©todo fit con la variable regresora X y la respuesta Y

X = df
X_test = dftest
Y = df["ArrDelay"] > 10
Y_test = dftest["ArrDelay"] > 10

clf = clf.fit(X, Y)
Y_pred = clf.predict(X)
Y_pred_test = clf.predict(X_test)